# Generated by Django 5.1.6 on 2025-02-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
    ]
